#!/bin/sh

# PROVIDE: tarbsd-zpool
# REQUIRE: mountcritlocal
# BEFORE: zfsbe zfs

. /etc/rc.subr

name=tarbsd_zpool
desc="imports attached zpools"
rcvar=tarbsd_zpool_enable

start_cmd="${name}_start"

tarbsd_zpool_start()
{
    if [ -f /sbin/zpool ]; then
        for pool in ${tarbsd_zpools}; do
            /sbin/zpool import -f ${pool}
        done
    fi
}

run_rc_command "$1"
